<!-- WATERMARK -->
<div class="watermark">
    @if(file_exists($logoPath))
        <img src="{{ $logoPath }}" width="350">
    @endif
</div>

<!-- HEADER -->
<div class="header" style="margin-buttom: 20px;">
    @if(file_exists($logoPath))
        <img src="{{ $logoPath }}" height="50">
    @endif

    <h2>ANNEX SYSTEM</h2>

    <strong>Financial Report</strong><br>
    Ref: {{ $reportId }}<br>
    <br>
</div>
<hr style="margin-top:10px;">

<!-- FOOTER -->
<div class="footer">
    Generated on {{ $generatedDate }} at {{ $generatedTime }}
    | By {{ $reporterName }}
    | Page <span class="pagenum"></span>
</div>

<h3>Report Information</h3>
<p>
    <strong>Generated By:</strong> {{ $reporterName }}<br>
    <strong>Email:</strong> {{ $reporterEmail }}<br>
    <strong>Date:</strong> {{ $generatedDate }}<br>
    <strong>Time:</strong> {{ $generatedTime }}
</p>

<div class="bg-white p-8 rounded-2xl shadow mb-8">
    <h3 class="text-lg font-bold text-primary mb-4">Executive Financial Overview</h3>

    <p class="text-gray-700 leading-relaxed mb-6">
        During the selected period, total gross revenue was
        <strong>NGN {{ number_format($gross,2) }}</strong>.
        After discounts of
        <strong>NGN {{ number_format($discount,2) }}</strong>,
        net revenue stood at
        <strong>NGN {{ number_format($net,2) }}</strong>.

        Staff allocation was
        <strong>NGN {{ number_format($staffShare,2) }}</strong>,
        radiographers earned
        <strong>NGN {{ number_format($radiographerShare,2) }}</strong>,
        radiologists earned
        <strong>NGN {{ number_format($radiologistShare,2) }}</strong>,
        and Annex share totaled
        <strong>NGN {{ number_format($annexShare,2) }}</strong>.

        Operational expenses were
        <strong>NGN {{ number_format($totalExpense,2) }}</strong>,
        salary paid was
        <strong>NGN {{ number_format($salaryAmount ?? 0,2) }}</strong>,
        and total outflow was
        <strong>NGN {{ number_format($totalOutflow ?? $totalExpense,2) }}</strong>,
        resulting in a net profit of
        <strong class="{{ $profit >= 0 ? 'text-green-600' : 'text-red-600' }}">
            NGN {{ number_format($profit,2) }}
        </strong>.
    </p>

    <div class="bg-white p-6 rounded-xl shadow mb-8">
        <h4 class="font-semibold text-primary mb-3">Financial Interpretation</h4>

        <ul class="text-sm text-gray-700 space-y-2 list-disc list-inside">
            <li>Discount impact represents {{ $gross > 0 ? number_format(($discount/$gross)*100,2) : 0 }}% of total gross revenue.</li>
            <li>Staff earnings account for {{ $net > 0 ? number_format(($staffShare/$net)*100,2) : 0 }}% of net revenue as per allocation policy.</li>
            <li>Radiologist earnings account for {{ $net > 0 ? number_format(($radiologistShare/$net)*100,2) : 0 }}% of net revenue as per allocation policy.</li>
            <li>Radiographer earnings account for {{ $net > 0 ? number_format(($radiographerShare/$net)*100,2) : 0 }}% of net revenue as per allocation policy.</li>
            <li>Profit margin for this period is {{ $net > 0 ? number_format(($profit/$net)*100,2) : 0 }}%.</li>
            <li>Expense-to-revenue ratio stands at {{ $net > 0 ? number_format(($totalExpense/$net)*100,2) : 0 }}%.</li>
            <li>Salary-to-revenue ratio stands at {{ $net > 0 ? number_format((($salaryAmount ?? 0)/$net)*100,2) : 0 }}%.</li>
        </ul>
    </div>

    <h3>Financial Summary</h3>

    <table>
        <tr>
            <th>Gross Revenue</th><td>NGN {{ number_format($gross,2) }}</td>
            <th>Discount</th><td>NGN {{ number_format($discount,2) }}</td>
        </tr>
        <tr>
            <th>Net Revenue</th><td>NGN {{ number_format($net,2) }}</td>
            <th>Staff Share</th><td>NGN {{ number_format($staffShare,2) }}</td>
        </tr>
        <tr>
            <th>Annex Share</th><td>NGN {{ number_format($annexShare,2) }}</td>
            <th>Radiologist Share</th><td>NGN {{ number_format($radiologistShare,2) }}</td>
        </tr>
        <tr>
            <th>Radiographer Share</th><td>NGN {{ number_format($radiographerShare,2) }}</td>
            <th>Refunds</th><td>NGN {{ number_format($refundsTotal ?? 0,2) }}</td>
        </tr>
        <tr>
            <th>Total Expenses</th><td>NGN {{ number_format($totalExpense,2) }}</td>
            <th>Salary Paid</th><td>NGN {{ number_format($salaryAmount ?? 0,2) }}</td>
        </tr>
        <tr>
            <th>Total Outflow</th><td>NGN {{ number_format($totalOutflow ?? $totalExpense,2) }}</td>
            <th>Net Profit</th>
            <td style="color: {{ $profit >= 0 ? 'green' : 'red' }}" colspan="3">
                NGN {{ number_format($profit,2) }}
            </td>
        </tr>
    </table>

    @if(isset($chartImage))
        <h3 style="margin-top:20px;">Financial Chart</h3>
        <img src="{{ $chartImage }}" width="100%">
    @endif

    @if(isset($qrCode))
        <h3 style="margin-top:20px;">Verification QR Code</h3>
        <img src="data:image/png;base64, {!! $qrCode !!}" width="120">
    @endif

    <div class="signature">
        <strong>Authorized Signature:</strong>
        <div class="signature-line"></div>
    </div>
</div>
