<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">

<style>

/* PAGE MARGINS */


/* BODY */
body {
    font-family: DejaVu Sans, sans-serif;
    font-size: 12px;
    color: #333;
}


/* HEADER */
@page {
    margin: 140px 40px 90px 40px;
}

.header {
    position: fixed;
    top: -120px;
    left: 0;
    right: 0;
    height: 100px;
}

.footer {
    position: fixed;
    bottom: -70px;
    left: 0;
    right: 0;
    height: 50px;
}

.logo {
    height: 50px;
}

/* FOOTER */


/* PAGE NUMBER */
.pagenum:after {
    content: counter(page);
}

/* TABLE STYLE */
table {
    width: 100%;
    border-collapse: collapse;
    margin-top: 10px;
    page-break-inside: auto;
}

tr {
    page-break-inside: avoid;
    page-break-after: auto;
}
table, th, td {
    border: 1px solid #ccc;
}

th, td {
    padding: 6px;
}

th {
    background: #f2f2f2;
}

/* WATERMARK */
.watermark {
    position: fixed;
    top: 35%;
    left: 20%;
    opacity: 0.06;
    z-index: -1000;
}

.signature {
    margin-top: 40px;
}

.signature-line {
    border-top: 1px solid #000;
    width: 200px;
    margin-top: 40px;
}

</style>
</head>

<body>

<!-- WATERMARK -->
<div class="watermark">
    @if(file_exists($logoPath))
        <img src="{{ $logoPath }}" width="350">
    @endif
</div>

<!-- HEADER -->
<div class="header">
    @if(file_exists($logoPath))
        <img src="{{ $logoPath }}" class="logo"><br>
    @endif
    <strong>ANNEX SYSTEM</strong><br>
    Financial Report<br>
    Ref: {{ $reportId }}
    <p>
        {{ \Carbon\Carbon::parse($from)->format('d M Y') }}
        —
        {{ \Carbon\Carbon::parse($to)->format('d M Y') }}
    </p>

</div>

<!-- FOOTER -->
<div class="footer">
    Generated on {{ $generatedDate }} at {{ $generatedTime }}
    | By {{ $reporterName }}
    | Page <span class="pagenum"></span>
</div>

<!-- CONTENT -->

<h3>Report Information</h3>
<p>
    <strong>Generated By:</strong> {{ $reporterName }}<br>
    <strong>Email:</strong> {{ $reporterEmail }}<br>
    <strong>Date:</strong> {{ $generatedDate }}<br>
    <strong>Time:</strong> {{ $generatedTime }}
</p>

<div class="bg-white p-8 rounded-2xl shadow mb-8">

    <h3 class="text-lg font-bold text-primary mb-4">
        Executive Financial Overview
    </h3>

    <p class="text-gray-700 leading-relaxed mb-6">
        During the selected period, a total gross revenue of 
        <strong>₦{{ number_format($gross,2) }}</strong> 
        was generated. After applying total discounts of 
        <strong>₦{{ number_format($discount,2) }}</strong>, 
        the net revenue stood at 
        <strong>₦{{ number_format($net,2) }}</strong>.

        From this net revenue, the staff allocation (40%) amounted to 
        <strong>₦{{ number_format($staffShare,2) }}</strong>, 
        while the Annex share (60%) totaled 
        <strong>₦{{ number_format($annexShare,2) }}</strong>.

        Operational expenses during this period were 
        <strong>₦{{ number_format($totalExpense,2) }}</strong>, 
        resulting in a net profit of 
        <strong class="{{ $profit >= 0 ? 'text-green-600' : 'text-red-600' }}">
            ₦{{ number_format($profit,2) }}
        </strong>.
    </p>

    <div class="bg-white p-6 rounded-xl shadow mb-8">

    <h4 class="font-semibold text-primary mb-3">
        Financial Interpretation
    </h4>

    <ul class="text-sm text-gray-700 space-y-2 list-disc list-inside">
        <li>
            Discount impact represents 
            {{ $gross > 0 ? number_format(($discount/$gross)*100,2) : 0 }}% 
            of total gross revenue.
        </li>
        <li>
            Staff earnings account for 40% of net revenue as per allocation policy.
        </li>
        <li>
            Profit margin for this period is 
            {{ $net > 0 ? number_format(($profit/$net)*100,2) : 0 }}%.
        </li>
        <li>
            Expense-to-revenue ratio stands at 
            {{ $net > 0 ? number_format(($totalExpense/$net)*100,2) : 0 }}%.
        </li>
    </ul>

</div>

<h3>Financial Summary</h3>

<table>
<tr><th>Gross Revenue</th><td>₦{{ number_format($gross,2) }}</td></tr>
<tr><th>Discount</th><td>₦{{ number_format($discount,2) }}</td></tr>
<tr><th>Net Revenue</th><td>₦{{ number_format($net,2) }}</td></tr>
<tr><th>Staff Share (40%)</th><td>₦{{ number_format($staffShare,2) }}</td></tr>
<tr><th>Annex Share (60%)</th><td>₦{{ number_format($annexShare,2) }}</td></tr>
<tr><th>Total Expenses</th><td>₦{{ number_format($totalExpense,2) }}</td></tr>
<tr>
    <th>Net Profit</th>
    <td style="color: {{ $profit >= 0 ? 'green' : 'red' }}">
        ₦{{ number_format($profit,2) }}
    </td>
</tr>
</table>

@if(isset($chartImage))
    <h3 style="margin-top:20px;">Financial Chart</h3>
    <img src="{{ $chartImage }}" width="100%">
@endif

@if(isset($qrCode))
    <h3 style="margin-top:20px;">Verification QR Code</h3>
    <img src="data:image/png;base64, {!! $qrCode !!}" width="120">
@endif

<div class="signature">
    <strong>Authorized Signature:</strong>
    <div class="signature-line"></div>
</div>

</body>
</html>