@extends('layouts.app')

@section('page-title','Financial Reports')

@section('content')
<div class="flex gap-4 mb-6">
    <form method="POST" action="{{ route('admin.reports.pdf') }}" id="pdfForm">
        @csrf
        <input type="hidden" name="chart_image" id="chartImageInput">
        <input type="hidden" name="from" value="{{ $from }}">
        <input type="hidden" name="to" value="{{ $to }}">

        <button type="submit"
            onclick="prepareChartImage()"
            class="bg-red-600 text-white px-4 py-2 rounded-xl">
            Download PDF
        </button>
    </form>
</div>

<div class="bg-white p-8 rounded-2xl shadow mb-8">
    <h2 class="text-2xl font-bold text-primary mb-2">Financial Summary Report</h2>

    <p class="text-sm text-gray-600">
        Period: 
        <strong>{{ \Carbon\Carbon::parse($from)->format('d M Y') }}</strong>
        -
        <strong>{{ \Carbon\Carbon::parse($to)->format('d M Y') }}</strong>
    </p>

    <div class="bg-white p-6 rounded-xl shadow mb-8">
        <h4 class="font-semibold text-primary mb-4">Report Information</h4>

        <div class="grid md:grid-cols-2 gap-4 text-sm text-gray-700">
            <div><strong>Report ID:</strong> {{ $reportId }}</div>
            <div><strong>Generated On:</strong> {{ $generatedDate }} at {{ $generatedTime }}</div>
            <div><strong>Generated By:</strong> {{ $reporterName }}</div>
            <div><strong>Email:</strong> {{ $reporterEmail }}</div>
        </div>
    </div>
</div>

<div class="bg-white p-8 rounded-2xl shadow mb-8">
    <h3 class="text-lg font-bold text-primary mb-4">Executive Financial Overview</h3>

    <p class="text-gray-700 leading-relaxed mb-6">
        During the selected period, total gross revenue was
        <strong>NGN {{ number_format($gross,2) }}</strong>.
        After discounts of
        <strong>NGN {{ number_format($discount,2) }}</strong>,
        net revenue stood at
        <strong>NGN {{ number_format($net,2) }}</strong>.

        Staff allocation was
        <strong>NGN {{ number_format($staffShare,2) }}</strong>,
        radiologists earned
        <strong>NGN {{ number_format($radiologistShare,2) }}</strong>,
        radiographers earned
        <strong>NGN {{ number_format($radiographerShare,2) }}</strong>,
        and Annex share totaled
        <strong>NGN {{ number_format($annexShare,2) }}</strong>.

        During the selected period, total refunds were
        <strong>NGN {{ number_format($refundsTotal ?? 0,2) }}</strong>.

        Operational expenses were
        <strong>NGN {{ number_format($totalExpense,2) }}</strong>,
        salary paid was
        <strong>NGN {{ number_format($salaryAmount ?? 0,2) }}</strong>,
        and total outflow was
        <strong>NGN {{ number_format($totalOutflow ?? $totalExpense,2) }}</strong>.
        Net profit was
        <strong class="{{ $profit >= 0 ? 'text-green-600' : 'text-red-600' }}">
            NGN {{ number_format($profit,2) }}
        </strong>.
    </p>

    <div class="bg-white p-6 rounded-xl shadow mb-8">
        <h4 class="font-semibold text-primary mb-3">Financial Interpretation</h4>

        <ul class="text-sm text-gray-700 space-y-2 list-disc list-inside">
            <li>Discount impact represents {{ $gross > 0 ? number_format(($discount/$gross)*100,2) : 0 }}% of total gross revenue.</li>
            <li>Refunds reduced revenue by {{ $gross > 0 ? number_format((($refundsTotal ?? 0)/$gross)*100,2) : 0 }}% during the selected period.</li>
            <li>Staff earnings account for {{ $net > 0 ? number_format(($staffShare/$net)*100,2) : 0 }}% of net revenue as per allocation policy.</li>
            <li>Radiologist earnings account for {{ $net > 0 ? number_format(($radiologistShare/$net)*100,2) : 0 }}% of net revenue as per allocation policy.</li>
            <li>Radiographer earnings account for {{ $net > 0 ? number_format(($radiographerShare/$net)*100,2) : 0 }}% of net revenue as per allocation policy.</li>
            <li>Expense-to-revenue ratio stands at {{ $net > 0 ? number_format(($totalExpense/$net)*100,2) : 0 }}%.</li>
            <li>Salary-to-revenue ratio stands at {{ $net > 0 ? number_format((($salaryAmount ?? 0)/$net)*100,2) : 0 }}%.</li>
        </ul>
    </div>
</div>

<canvas id="reportChart"></canvas>
@endsection

@section('scripts')
<script>
    function prepareChartImage() {
        const canvas = document.getElementById('reportChart');
        const image = canvas.toDataURL("image/png");

        document.getElementById('chartImageInput').value = image;
    }
</script>

<script>
function renderReportChart() {
    new Chart(document.getElementById('reportChart'), {
        type: 'bar',
        data: {
            labels: ['Gross','Discount','Staff Share','Radiologist Share','Radiographer Share','Annex Share','Expenses','Salary','Profit'],
            datasets: [{
                data: [
                    {{ $gross }},
                    {{ $discount }},
                    {{ $staffShare }},
                    {{ $radiologistShare }},
                    {{ $radiographerShare }},
                    {{ $annexShare }},
                    {{ $totalExpense }},
                    {{ $salaryAmount ?? 0 }},
                    {{ $profit }}
                ],
                backgroundColor: [
                    '#1E4E8C',
                    '#F59E0B',
                    '#16A34A',
                    '#0F2D5C',
                    '#DC2626',
                    '#10B981',
                    '#3B82F6',
                    '#D97706',
                    '{{ $profit >= 0 ? "#34D399" : "#F87171"}}'
                ]
            }]
        }
    });
}

if (window.Chart) {
    renderReportChart();
} else {
    window.addEventListener('app-assets-ready', renderReportChart, { once: true });
}
</script>
@endsection
