@extends('layouts.app')

@section('page-title','Financial Reports')

@section('content')
<div class="flex gap-4 mb-6">
    <form method="POST" action="{{ route('admin.reports.pdf') }}" id="pdfForm">
        @csrf
        <input type="hidden" name="chart_image" id="chartImageInput">
        <input type="hidden" name="from" value="{{ $from }}">
        <input type="hidden" name="to" value="{{ $to }}">

        <button type="submit"
            onclick="prepareChartImage()"
            class="bg-red-600 text-white px-4 py-2 rounded-xl">
            Download PDF
        </button>
    </form>

    <a href="{{ route('admin.reports.csv',['from'=>$from,'to'=>$to]) }}"
        class="bg-green-600 text-white px-4 py-2 rounded-xl">
        Download CSV
    </a>

    <form method="POST" action="{{ route('admin.reports.excel') }}">
        @csrf
        <input type="hidden" name="from" value="{{ $from }}">
        <input type="hidden" name="to" value="{{ $to }}">

        <button class="bg-green-600 text-white px-4 py-2 rounded-xl">
            Download Excel
        </button>
    </form>

</div>
<div class="bg-white p-8 rounded-2xl shadow mb-8">

    <!-- REPORT HEADER -->
    <h2 class="text-2xl font-bold text-primary mb-2">
        Financial Summary Report
    </h2>

    <p class="text-sm text-gray-600">
        Period: 
        <strong>{{ \Carbon\Carbon::parse($from)->format('d M Y') }}</strong>
        —
        <strong>{{ \Carbon\Carbon::parse($to)->format('d M Y') }}</strong>
    </p>
    <div class="bg-white p-6 rounded-xl shadow mb-8">

        <h4 class="font-semibold text-primary mb-4">
            Report Information
        </h4>

        <div class="grid md:grid-cols-2 gap-4 text-sm text-gray-700">

            <div>
                <strong>Report ID:</strong> {{ $reportId }}
            </div>

            <div>
                <strong>Generated On:</strong> 
                {{ $generatedDate }} at {{ $generatedTime }}
            </div>

            <div>
                <strong>Generated By:</strong> {{ $reporterName }}
            </div>

            <div>
                <strong>Email:</strong> {{ $reporterEmail }}
            </div>

        </div>

    </div>

</div>
<div class="bg-white p-8 rounded-2xl shadow mb-8">

    <h3 class="text-lg font-bold text-primary mb-4">
        Executive Financial Overview
    </h3>

    <p class="text-gray-700 leading-relaxed mb-6">
        During the selected period, a total gross revenue of 
        <strong>₦{{ number_format($gross,2) }}</strong> 
        was generated. After applying total discounts of 
        <strong>₦{{ number_format($discount,2) }}</strong>, 
        the net revenue stood at 
        <strong>₦{{ number_format($net,2) }}</strong>.

        From this net revenue, the staff allocation (40%) amounted to 
        <strong>₦{{ number_format($staffShare,2) }}</strong>, 
        while the Annex share (60%) totaled 
        <strong>₦{{ number_format($annexShare,2) }}</strong>.

        Operational expenses during this period were 
        <strong>₦{{ number_format($totalExpense,2) }}</strong>, 
        resulting in a net profit of 
        <strong class="{{ $profit >= 0 ? 'text-green-600' : 'text-red-600' }}">
            ₦{{ number_format($profit,2) }}
        </strong>.
    </p>

    <div class="bg-white p-6 rounded-xl shadow mb-8">

    <h4 class="font-semibold text-primary mb-3">
        Financial Interpretation
    </h4>

    <ul class="text-sm text-gray-700 space-y-2 list-disc list-inside">
        <li>
            Discount impact represents 
            {{ $gross > 0 ? number_format(($discount/$gross)*100,2) : 0 }}% 
            of total gross revenue.
        </li>
        <li>
            Staff earnings account for 40% of net revenue as per allocation policy.
        </li>
        <li>
            Profit margin for this period is 
            {{ $net > 0 ? number_format(($profit/$net)*100,2) : 0 }}%.
        </li>
        <li>
            Expense-to-revenue ratio stands at 
            {{ $net > 0 ? number_format(($totalExpense/$net)*100,2) : 0 }}%.
        </li>
    </ul>

</div>

</div>



<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<canvas id="reportChart"></canvas>
@endsection

@section('scripts')
<script>
    function prepareChartImage() {
        const canvas = document.getElementById('reportChart');
        const image = canvas.toDataURL("image/png");

        document.getElementById('chartImageInput').value = image;
    }
</script>

<script>
new Chart(document.getElementById('reportChart'), {
    type: 'bar',
    data: {
        labels: ['Gross','Discount','Staff Share','Annex Share','Expenses','Profit'],
        datasets: [{
            data: [
                {{ $gross }},
                {{ $discount }},
                {{ $staffShare }},
                {{ $annexShare }},
                {{ $totalExpense }},
                {{ $profit }}
            ],
            backgroundColor: [
                '#1E4E8C',
                '#F59E0B',
                '#16A34A',
                '#0F2D5C',
                '#DC2626',
                '#10B981'
            ]
        }]
    }
});
</script>
@endsection