<?php

namespace App\Exports\Sheets;

use App\Models\Bill;
use App\Models\Expense;
use Illuminate\Support\Collection;
use Maatwebsite\Excel\Concerns\FromArray;
use Maatwebsite\Excel\Concerns\WithEvents;
use Maatwebsite\Excel\Concerns\WithDrawings;
use Maatwebsite\Excel\Events\AfterSheet;
use PhpOffice\PhpSpreadsheet\Worksheet\Drawing;
use PhpOffice\PhpSpreadsheet\Chart\Chart;
use PhpOffice\PhpSpreadsheet\Chart\DataSeries;
use PhpOffice\PhpSpreadsheet\Chart\DataSeriesValues;
use PhpOffice\PhpSpreadsheet\Chart\PlotArea;
use PhpOffice\PhpSpreadsheet\Chart\Legend;
use PhpOffice\PhpSpreadsheet\Chart\Title;

class Summary implements FromArray, WithEvents, WithDrawings
{
    protected $from;
    protected $to;
    protected $reportId;

    public function __construct($from, $to, $reportId)
    {
        $this->from = $from;
        $this->to = $to;
        $this->reportId = $reportId;
    }

    public function array(): array
    {
        $bills = Bill::whereBetween('created_at', [$this->from,$this->to])->get();
        $expenses = Expense::whereBetween('expense_date', [$this->from,$this->to])->get();

        $gross = $bills->sum('total_amount');
        $discount = $bills->sum('discount_amount');

        return [
            ['ANNEX SYSTEM FINANCIAL REPORT'],
            ['Report Reference', $this->reportId],
            ['Generated By', auth()->user()->name],
            ['Email', auth()->user()->email],
            ['Period', "$this->from - $this->to"],
            [],
            ['FINANCIAL SUMMARY'],
            ['Gross Revenue', $gross],        // Row 8
            ['Discount', $discount],          // Row 9
            ['Net Revenue', '=B8-B9'],        // Row 10
            ['Staff Share (40%)', '=B10*0.4'],// Row 11
            ['Annex Share (60%)', '=B10*0.6'],// Row 12
            ['Expenses', $expenses->sum('amount')], // Row 13
            ['Net Profit', '=B12-B13'],       // Row 14
        ];
    }

    /* ---------- STYLING ---------- */
    public function registerEvents(): array
    {
        return [
            AfterSheet::class => function(AfterSheet $event) {

                // Bold title
                $event->sheet->getStyle('A1')
                    ->getFont()->setBold(true)->setSize(16);

                // Bold financial labels
                $event->sheet->getStyle('A7:A13')
                    ->getFont()->setBold(true);

                // Currency format
                $event->sheet->getStyle('B7:B13')
                    ->getNumberFormat()
                    ->setFormatCode('#,##0.00');

                // Auto column width
                $event->sheet->getDelegate()->getColumnDimension('A')->setAutoSize(true);
                $event->sheet->getDelegate()->getColumnDimension('B')->setAutoSize(true);

                /* ---------- ADD CHART ---------- */
                $dataSeriesLabels = [
                    new DataSeriesValues('String', 'Summary!$A$7:$A$13', null, 7),
                ];

                $xAxisTickValues = [
                    new DataSeriesValues('String', 'Summary!$A$7:$A$13', null, 7),
                ];

                $dataSeriesValues = [
                    new DataSeriesValues('Number', 'Summary!$B$7:$B$13', null, 7),
                ];

                $series = new DataSeries(
                    DataSeries::TYPE_BARCHART,
                    DataSeries::GROUPING_CLUSTERED,
                    range(0, count($dataSeriesValues)-1),
                    $dataSeriesLabels,
                    $xAxisTickValues,
                    $dataSeriesValues
                );

                $plotArea = new PlotArea(null, [$series]);
                $legend = new Legend(Legend::POSITION_RIGHT, null, false);
                $title = new Title('Financial Overview');

                $chart = new Chart(
                    'Financial Chart',
                    $title,
                    $legend,
                    $plotArea
                );

                $chart->setTopLeftPosition('D7');
                $chart->setBottomRightPosition('L20');

                $event->sheet->getDelegate()->addChart($chart);
            },
        ];
    }

    /* ---------- LOGO ---------- */
    public function drawings()
    {
        $drawing = new Drawing();
        $drawing->setName('Company Logo');
        $drawing->setDescription('Logo');
        $drawing->setPath(public_path('images/logo.png'));
        $drawing->setHeight(60);
        $drawing->setCoordinates('D1');

        return $drawing;
    }
}