<?php

namespace App\Exports\Sheets;

use App\Models\Bill;
use App\Models\BillRefund;
use App\Models\Expense;
use Illuminate\Support\Collection;
use Maatwebsite\Excel\Concerns\FromArray;
use Maatwebsite\Excel\Concerns\WithEvents;
use Maatwebsite\Excel\Concerns\WithDrawings;
use Maatwebsite\Excel\Events\AfterSheet;
use PhpOffice\PhpSpreadsheet\Worksheet\Drawing;
use PhpOffice\PhpSpreadsheet\Chart\Chart;
use PhpOffice\PhpSpreadsheet\Chart\DataSeries;
use PhpOffice\PhpSpreadsheet\Chart\DataSeriesValues;
use PhpOffice\PhpSpreadsheet\Chart\PlotArea;
use PhpOffice\PhpSpreadsheet\Chart\Legend;
use PhpOffice\PhpSpreadsheet\Chart\Title;

class Summary implements FromArray, WithEvents, WithDrawings
{
    protected $from;
    protected $to;
    protected $reportId;
    protected $isAdmin;

    public function __construct($from, $to, $reportId, $isAdmin = false)
    {
        $this->from = $from;
        $this->to = $to;
        $this->reportId = $reportId;
        $this->isAdmin = $isAdmin;
    }

    public function array(): array
    {
        $billsQuery = Bill::with('items.revenueDistribution')->whereBetween('created_at', [$this->from,$this->to]);
        $expensesQuery = Expense::whereBetween('expense_date', [$this->from,$this->to]);
        $refundsQuery = BillRefund::whereBetween('created_at', [$this->from,$this->to]);
        
        // If not admin, only fetch own data
        if (!$this->isAdmin) {
            $billsQuery->where('user_id', auth()->id());
            $expensesQuery->where('user_id', auth()->id());
            $refundsQuery->where('user_id', auth()->id());
        }
        
        $bills = $billsQuery->get();
        $expenses = $expensesQuery->get();
        $refundsTotal = $refundsQuery->sum('amount');

        $gross = $bills->sum('total_amount');
        $discount = $bills->sum('discount_amount');
        $net = $gross - $discount - $refundsTotal;

        // Calculate shares based on actual distributions
        $staffShare = 0;
        $annexShare = 0;
        $radiologistShare = 0;
        $radiographerShare = 0;
        foreach ($bills as $bill) {
            foreach ($bill->items as $item) {
                $distribution = $item->revenueDistribution;
                if ($distribution) {
                    $staffShare += $distribution->staff_amount;
                    $annexShare += $distribution->annex_amount;
                    $radiologistShare += $distribution->radiologist_amount;
                    $radiographerShare += $distribution->radiographer_amount;
                }
            }
        }

        $totalExpense = $expenses->sum('amount');
        $profit = $annexShare - $totalExpense;

        return [
            ['ANNEX SYSTEM FINANCIAL REPORT'],
            ['Report Reference', $this->reportId],
            ['Generated By', auth()->user()->name],
            ['Email', auth()->user()->email],
            ['Period', "$this->from - $this->to"],
            [],
            ['FINANCIAL SUMMARY'],
            ['Gross Revenue', $gross],        // Row 8
            ['Discount', $discount],          // Row 9
            ['Refunds', $refundsTotal],       // Row 10
            ['Net Revenue', $net],            // Row 11
            ['Staff Share', $staffShare],     // Row 12
            ['Annex Share', $annexShare],     // Row 13
            ['Radiologist Share', $radiologistShare], // Row 14
            ['Radiographer Share', $radiographerShare], // Row 15
            ['Expenses', $totalExpense],      // Row 16
            ['Net Profit', $profit],          // Row 17
        ];
    }

    /* ---------- STYLING ---------- */
    public function registerEvents(): array
    {
        return [
            AfterSheet::class => function(AfterSheet $event) {

                // Bold title
                $event->sheet->getStyle('A1')
                    ->getFont()->setBold(true)->setSize(16);

                // Bold financial labels
                $event->sheet->getStyle('A7:A17')
                    ->getFont()->setBold(true);

                // Currency format
                $event->sheet->getStyle('B7:B17')
                    ->getNumberFormat()
                    ->setFormatCode('#,##0.00');

                // Auto column width
                $event->sheet->getDelegate()->getColumnDimension('A')->setAutoSize(true);
                $event->sheet->getDelegate()->getColumnDimension('B')->setAutoSize(true);

                /* ---------- ADD CHART ---------- */
                $dataSeriesLabels = [
                    new DataSeriesValues('String', 'Summary!$A$7:$A$17', null, 11),
                ];

                $xAxisTickValues = [
                    new DataSeriesValues('String', 'Summary!$A$7:$A$17', null, 11),
                ];

                $dataSeriesValues = [
                    new DataSeriesValues('Number', 'Summary!$B$7:$B$17', null, 11),
                ];

                $series = new DataSeries(
                    DataSeries::TYPE_BARCHART,
                    DataSeries::GROUPING_CLUSTERED,
                    range(0, count($dataSeriesValues)-1),
                    $dataSeriesLabels,
                    $xAxisTickValues,
                    $dataSeriesValues
                );

                $plotArea = new PlotArea(null, [$series]);
                $legend = new Legend(Legend::POSITION_RIGHT, null, false);
                $title = new Title('Financial Overview');

                $chart = new Chart(
                    'Financial Chart',
                    $title,
                    $legend,
                    $plotArea
                );

                $chart->setTopLeftPosition('D7');
                $chart->setBottomRightPosition('L20');

                $event->sheet->getDelegate()->addChart($chart);
            },
        ];
    }

    /* ---------- LOGO ---------- */
    public function drawings()
    {
        $drawing = new Drawing();
        $drawing->setName('Company Logo');
        $drawing->setDescription('Logo');
        $drawing->setPath(public_path('images/logo.png'));
        $drawing->setHeight(60);
        $drawing->setCoordinates('D1');

        return $drawing;
    }
}