<?php

namespace App\Exports\Sheets;

use App\Models\Bill;
use App\Models\BillRefund;
use App\Models\Expense;
use App\Models\SalaryPayment;
use Carbon\Carbon;
use Illuminate\Support\Collection;
use Maatwebsite\Excel\Concerns\FromArray;
use Maatwebsite\Excel\Concerns\WithEvents;
use Maatwebsite\Excel\Concerns\WithDrawings;
use Maatwebsite\Excel\Events\AfterSheet;
use PhpOffice\PhpSpreadsheet\Worksheet\Drawing;
use PhpOffice\PhpSpreadsheet\Chart\Chart;
use PhpOffice\PhpSpreadsheet\Chart\DataSeries;
use PhpOffice\PhpSpreadsheet\Chart\DataSeriesValues;
use PhpOffice\PhpSpreadsheet\Chart\PlotArea;
use PhpOffice\PhpSpreadsheet\Chart\Legend;
use PhpOffice\PhpSpreadsheet\Chart\Title;

class Summary implements FromArray, WithEvents, WithDrawings
{
    protected $from;
    protected $to;
    protected $reportId;
    protected $isAdmin;

    public function __construct($from, $to, $reportId, $isAdmin = false)
    {
        $this->from = $from;
        $this->to = $to;
        $this->reportId = $reportId;
        $this->isAdmin = $isAdmin;
    }

    public function array(): array
    {
        $billsQuery = Bill::with('items.revenueDistribution')->whereBetween('created_at', [$this->from,$this->to]);
        $expensesQuery = Expense::whereBetween('expense_date', [$this->from,$this->to]);
        $refundsQuery = BillRefund::whereBetween('created_at', [$this->from,$this->to]);

        if (!$this->isAdmin) {
            $billsQuery->where('user_id', auth()->id());
            $expensesQuery->where('user_id', auth()->id());
            $refundsQuery->where('user_id', auth()->id());
        }

        $bills = $billsQuery->get();
        $expenses = $expensesQuery->get();
        $refundsTotal = $refundsQuery->sum('amount');

        $gross = $bills->sum('total_amount');
        $discount = $bills->sum('discount_amount');
        $net = $gross - $discount - $refundsTotal;

        $staffShare = 0;
        $annexShare = 0;
        $radiologistShare = 0;
        $radiographerShare = 0;
        foreach ($bills as $bill) {
            foreach ($bill->items as $item) {
                $distribution = $item->revenueDistribution;
                if ($distribution) {
                    $staffShare += $distribution->staff_amount;
                    $annexShare += $distribution->annex_amount;
                    $radiologistShare += $distribution->radiologist_amount;
                    $radiographerShare += $distribution->radiographer_amount;
                }
            }
        }

        $totalExpense = $expenses->sum('amount');
        $salaryAmount = $this->salaryAmountForRange();
        $totalOutflow = $totalExpense + $salaryAmount + $refundsTotal;
        $profit = $annexShare - $totalOutflow;

        return [
            ['ANNEX SYSTEM FINANCIAL REPORT'],
            ['Report Reference', $this->reportId],
            ['Generated By', auth()->user()->name],
            ['Email', auth()->user()->email],
            ['Period', "$this->from - $this->to"],
            [],
            ['FINANCIAL SUMMARY'],
            ['Gross Revenue', $gross],
            ['Discount', $discount],
            ['Refunds', $refundsTotal],
            ['Net Revenue', $net],
            ['Staff Share', $staffShare],
            ['Annex Share', $annexShare],
            ['Radiologist Share', $radiologistShare],
            ['Radiographer Share', $radiographerShare],
            ['Expenses', $totalExpense],
            ['Salary', $salaryAmount],
            ['Total Outflow', $totalOutflow],
            ['Net Profit', $profit],
        ];
    }

    /* ---------- STYLING ---------- */
    public function registerEvents(): array
    {
        return [
            AfterSheet::class => function(AfterSheet $event) {

                $event->sheet->getStyle('A1')
                    ->getFont()->setBold(true)->setSize(16);

                $event->sheet->getStyle('A7:A18')
                    ->getFont()->setBold(true);

                $event->sheet->getStyle('B7:B18')
                    ->getNumberFormat()
                    ->setFormatCode('#,##0.00');

                $event->sheet->getDelegate()->getColumnDimension('A')->setAutoSize(true);
                $event->sheet->getDelegate()->getColumnDimension('B')->setAutoSize(true);

                $dataSeriesLabels = [
                    new DataSeriesValues('String', 'Summary!$A$7:$A$18', null, 12),
                ];

                $xAxisTickValues = [
                    new DataSeriesValues('String', 'Summary!$A$7:$A$18', null, 12),
                ];

                $dataSeriesValues = [
                    new DataSeriesValues('Number', 'Summary!$B$7:$B$18', null, 12),
                ];

                $series = new DataSeries(
                    DataSeries::TYPE_BARCHART,
                    DataSeries::GROUPING_CLUSTERED,
                    range(0, count($dataSeriesValues)-1),
                    $dataSeriesLabels,
                    $xAxisTickValues,
                    $dataSeriesValues
                );

                $plotArea = new PlotArea(null, [$series]);
                $legend = new Legend(Legend::POSITION_RIGHT, null, false);
                $title = new Title('Financial Overview');

                $chart = new Chart(
                    'Financial Chart',
                    $title,
                    $legend,
                    $plotArea
                );

                $chart->setTopLeftPosition('D7');
                $chart->setBottomRightPosition('L20');

                $event->sheet->getDelegate()->addChart($chart);
            },
        ];
    }

    /* ---------- LOGO ---------- */
    public function drawings()
    {
        $drawing = new Drawing();
        $drawing->setName('Company Logo');
        $drawing->setDescription('Logo');
        $drawing->setPath(public_path('images/logo.png'));
        $drawing->setHeight(60);
        $drawing->setCoordinates('D1');

        return $drawing;
    }

    private function salaryAmountForRange(): float
    {
        if (! $this->isAdmin || ! $this->from || ! $this->to) {
            return 0;
        }

        $fromMonth = Carbon::parse($this->from)->startOfMonth()->toDateString();
        $toMonth = Carbon::parse($this->to)->startOfMonth()->toDateString();

        return (float) SalaryPayment::whereBetween('salary_month', [$fromMonth, $toMonth])
            ->sum('amount');
    }
}
